feat:migrations config
SAB-UFBA2022/backend pull request #15
Opened 2022-09-19 00:11 UTC by brenordp

# ✏📝 Descreva as mudanças que esse Pull Request implementa
### Descreva aqui

## O que esse PR representa?
- [ ] Bug fix(mudança ininterrupta que corrige um problema) 🐞
- [ ] New Feature/Novo recurso (mudança ininterrupta que adiciona funcionalidade) ⚙
- [ ] Mudança de última hora (correção ou recurso que faria com que a funcionalidade existente não funcionasse conforme o esperado) ⏰
- [ ] Alteração de documentação 📝

# Checklist:

- [ ] Adicionei testes que comprovam que minha correção é eficaz ou que meu recurso funciona 🧪
- [ ] Testes de unidade novos e existentes são aprovados localmente com minhas alterações 🧪
- [ ] Meu código segue as diretrizes de estilo deste projeto 📏
- [ ] Realizei uma auto-revisão do meu próprio código 👨‍🏫👩‍🏫
- [ ] Removi arquivos inutilizados ♻
- [ ] Fiz as alterações correspondentes com a minha task 🙏
- [ ] Minhas alterações não geram novos problemas 🙏

2022-09-19 21:06 UTC, brunodelucasbarbosa requested changes

2022-09-19 21:06 UTC, brunodelucasbarbosa commented on .env.example
> +DATABASE_HOST=
Esse `DATABASE_HOST` teria a mesma finalidade do `HOST` ?
Acredito ter sido uma má escolha de nome realmente, mas, isso pode quebrar o deploy já feito, melhor manter como HOST
Já tivemos umas perdas no deploy kkk

2022-09-19 21:06 UTC, brunodelucasbarbosa commented on src/config/ormconfig.ts
> +  synchronize: false,
Tendo a migration, nao precisa do syncronize né?

2022-09-19 21:06 UTC, brunodelucasbarbosa commented on src/database/database.module.ts
> -        ssl: configService.get('MODE') === 'prod',
Isso aqui é importante manter!!!

2022-09-19 21:07 UTC, brunodelucasbarbosa commented
E lembrar de dar o pull

2022-09-20 11:56 UTC, brenordp commented on src/config/ormconfig.ts
> +  synchronize: false,
isso, vi q syncronize era pouco indicado pra coisas em production etc. Acho q a ideia é sempre rodar as migrations msm no banco de prod. Syncronize pode gerar perda de dados

2022-09-20 11:57 UTC, brenordp commented on src/database/database.module.ts
> -        ssl: configService.get('MODE') === 'prod',
hmm, okok. Pode me dizer pra q serve? nunca tinha visto isso, acabei n pesquisando tb

2022-09-20 12:00 UTC, brenordp commented on .env.example
> +DATABASE_HOST=
Mudei!

2022-09-20 13:21 UTC, brunodelucasbarbosa commented on src/database/database.module.ts
> -        ssl: configService.get('MODE') === 'prod',
Isso é pra poder indicar se está em prod ou não, para que no deploy o banco se conecte sem problemas e localmente não atrapalhe o banco que já existe, só deixar lá que tá suave se não o deploy quebra kk

2022-09-20 13:23 UTC, brenordp commented on src/database/database.module.ts
> -        ssl: configService.get('MODE') === 'prod',
já coloquei de novo

2022-09-20 13:45 UTC, brunodelucasbarbosa approved these changes

2022-09-20 13:45 UTC, merged