Feat/recovery password
SAB-UFBA2022/backend pull request #16
Opened 2022-09-19 02:06 UTC by brenordp

# ✏📝 Descreva as mudanças que esse Pull Request implementa
### Descreva aqui

## O que esse PR representa?
- [ ] Bug fix(mudança ininterrupta que corrige um problema) 🐞
- [ ] New Feature/Novo recurso (mudança ininterrupta que adiciona funcionalidade) ⚙
- [ ] Mudança de última hora (correção ou recurso que faria com que a funcionalidade existente não funcionasse conforme o esperado) ⏰
- [ ] Alteração de documentação 📝

# Checklist:

- [ ] Adicionei testes que comprovam que minha correção é eficaz ou que meu recurso funciona 🧪
- [ ] Testes de unidade novos e existentes são aprovados localmente com minhas alterações 🧪
- [ ] Meu código segue as diretrizes de estilo deste projeto 📏
- [ ] Realizei uma auto-revisão do meu próprio código 👨‍🏫👩‍🏫
- [ ] Removi arquivos inutilizados ♻
- [ ] Fiz as alterações correspondentes com a minha task 🙏
- [ ] Minhas alterações não geram novos problemas 🙏

2022-09-19 21:16 UTC, brunodelucasbarbosa requested changes
A remoção do `useGlobalPipes` foi acidental? ou por dar algum erro? pq sem ele não vai ter problemas com as validações?

2022-09-19 21:16 UTC, brunodelucasbarbosa commented on src/main.ts
> -  app.useGlobalPipes(
A remoção desse trecho não vai gerar problemas com as validação e o cors?

2022-09-19 22:12 UTC, brunodelucasbarbosa commented
Dessa forma que está, o usuário cadastra uma nova senha, correto?

2022-09-20 11:54 UTC, brenordp commented on src/main.ts
> -  app.useGlobalPipes(
Não sei exatamente oq essa linha fazia, tive que tirar pra conseguir testar os endpoints q eu estava criando. Acho que com isso atualmente todos os endpoints estão precisando ter authorização? não entendi direito só estava tomando sempre bad request com uma mensagem esquisita.

2022-09-20 11:55 UTC, brenordp commented
Sim, ele da update na senha dele.

2022-09-20 13:22 UTC, brunodelucasbarbosa commented on src/main.ts
> -  app.useGlobalPipes(
Esse trecho é para o class-validator, as regras de input dependem dele, vamos tentar refazer os fluxos que tu fez, pra eu testar aqui também, pq se tirar isso vai dar ruim, e vamos descobrir o motivo dos erros

2022-09-20 13:23 UTC, brunodelucasbarbosa commented
> Sim, ele da update na senha dele.

aa blz, o professor tinha dito que poderia só enviar a senha antiga pro email (na minha visão uma forma bem ruim)
dessa sua forma é o ideal mesmo kspakskap

2022-09-20 13:23 UTC, brunodelucasbarbosa requested changes
comentários

2022-09-20 13:26 UTC, brenordp commented on src/main.ts
> -  app.useGlobalPipes(
coloquei de volta!

2022-09-20 13:46 UTC, brunodelucasbarbosa approved these changes

2022-09-20 13:46 UTC, brunodelucasbarbosa commented
@brenordp só fazer o pull e mergear, n consigo pq tem que estar atualizado

2022-09-20 13:53 UTC, merged