Adição do novo módulo de `agência`
SAB-UFBA2022/backend pull request #17
Opened 2022-09-19 02:32 UTC by gabrielsoaresm94

# ✏📝 Descreva as mudanças que esse Pull Request implementa
### Descreva aqui

## O que esse PR representa?
- [ ] Bug fix(mudança ininterrupta que corrige um problema) 🐞
- [x] New Feature/Novo recurso (mudança ininterrupta que adiciona funcionalidade) ⚙
- [ ] Mudança de última hora (correção ou recurso que faria com que a funcionalidade existente não funcionasse conforme o esperado) ⏰
- [ ] Alteração de documentação 📝

# Checklist:

- [x] Adicionei testes que comprovam que minha correção é eficaz ou que meu recurso funciona 🧪
- [x] Testes de unidade novos e existentes são aprovados localmente com minhas alterações 🧪
- [x] Meu código segue as diretrizes de estilo deste projeto 📏
- [ ] Realizei uma auto-revisão do meu próprio código 👨‍🏫👩‍🏫
- [ ] Removi arquivos inutilizados ♻
- [x] Fiz as alterações correspondentes com a minha task 🙏
- [x] Minhas alterações não geram novos problemas 🙏

2022-09-19 21:12 UTC, brunodelucasbarbosa requested changes

2022-09-19 21:12 UTC, brunodelucasbarbosa commented on src/agency/controller/agency.controller.ts
> +@Controller('v1/article')
Mapeando para a rota de article

2022-09-19 21:12 UTC, brunodelucasbarbosa commented on src/agency/entities/agency.entity.ts
> +export class AgencyEntity {
Faltou o relacionamento da agência seguindo o modelo
não deveria ter nas duas pontas?

2022-10-29 20:45 UTC, gabrielsoaresm94 commented on src/agency/controller/agency.controller.ts
> +@Controller('v1/article')
Resolvido.

2022-10-29 20:59 UTC, gabrielsoaresm94 commented on src/agency/entities/agency.entity.ts
> +export class AgencyEntity {
Resolvido, relacionamentos adicionados nas duas pontas.

2022-11-09 16:53 UTC, gustavooquinteiro approved these changes

2022-11-10 01:01 UTC, brunodelucasbarbosa requested changes
As mudanças que mencionei são ajustes que precisam estar, não necessariamente deveriam estar imediatamente nesse mr, mas, o mais rápido possível pois o front precisa disso! 
Além disso, não está funcionando, precisa rever isso, não dá pra subir se não estiver funcionando

2022-11-21 23:47 UTC, merged