feat: update student
SAB-UFBA2022/backend pull request #26
Opened 2022-09-26 02:27 UTC by brenorosas

# ✏📝 Descreva as mudanças que esse Pull Request implementa
### Descreva aqui

## O que esse PR representa?
- [ ] Bug fix(mudança ininterrupta que corrige um problema) 🐞
- [ ] New Feature/Novo recurso (mudança ininterrupta que adiciona funcionalidade) ⚙
- [ ] Mudança de última hora (correção ou recurso que faria com que a funcionalidade existente não funcionasse conforme o esperado) ⏰
- [ ] Alteração de documentação 📝

# Checklist:

- [ ] Adicionei testes que comprovam que minha correção é eficaz ou que meu recurso funciona 🧪
- [ ] Testes de unidade novos e existentes são aprovados localmente com minhas alterações 🧪
- [ ] Meu código segue as diretrizes de estilo deste projeto 📏
- [ ] Realizei uma auto-revisão do meu próprio código 👨‍🏫👩‍🏫
- [ ] Removi arquivos inutilizados ♻
- [ ] Fiz as alterações correspondentes com a minha task 🙏
- [ ] Minhas alterações não geram novos problemas 🙏

2022-09-26 14:35 UTC, brunodelucasbarbosa requested changes

2022-10-13 14:17 UTC, brunodelucasbarbosa requested changes

2022-10-13 14:17 UTC, brunodelucasbarbosa commented on src/students/service/students.service.ts
> +  async updateStudent(student: CreateStudentDTO) {
@brenorosas Ele tá puxando do CreateStudentDTO, então ele requer todas as informações de cadastro, como por exemplo a bolsa, a bolsa será editada em outro endpoint, pq nesse casoe la n será usada

2022-10-22 11:51 UTC, brenorosas commented on src/students/service/students.service.ts
> +  async updateStudent(student: CreateStudentDTO) {
E quais são os campos que queremos q seja editável ?

2022-10-23 22:36 UTC, brunodelucasbarbosa approved these changes

2022-10-23 22:57 UTC, merged